<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="aircraft.aspx.cs" Inherits="airline_management_system.aircraft" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
        <title> Aircraft Form </title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <style type="text/css">
            .bg{
                background-image: linear-gradient(90deg,#12c2e9,#c471ed,#f64f59);
            }
            h1{
               /* text-decoration:underline 1px;*/
                padding:40px 0px 30px 0px;
            }
            .table-bg {
                background: rgba(255,255,255,0.31);
                box-shadow: 0 4px 30px rgba(0,0,0,0.1);
                backdrop-filter: blur(4.5px);
                -webkit-backdrop-filter: blur(4.5px);
               /* border: 1px solid rgba(255,255,255,1);*/
                text-align: center;
                border-radius: 16px;
                margin: 120px auto;
                width:800px;
            }
            tr{
                padding:200px;
            }

    </style>
</head>
<body class="bg">
    <form id="form1" runat="server">
        <div>
            <table class="table-bg">
                <tr>
                    <td  colspan="2">
                        <h1>Aircraft Details</h1>
                    </td>
                </tr>
                <tr>
                    <td >
                        <h4>Aircraft Id :</h4>
                    </td>
                    <td>
                        <asp:TextBox ID="txtaircraftid" CssClass="form-control my-2 w-75" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td ><h4> Model :</h4></td>
                    <td>
                        <asp:TextBox ID="txtmodel" CssClass="form-control my-2 w-75" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td><h4> Capacity :</h4></td>
                    <td>
                        <asp:TextBox ID="txtcapacity" CssClass="form-control my-2 w-75" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td ><h4> Airline Code :</h4></td>
                    <td>
                        <asp:DropDownList ID="ddlairlinecode" CssClass="form-control my-2 w-75" runat="server">
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" CssClass="d-flex justify-content-between">
                        <asp:Button ID="btnadd" CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Add Aircraft"  />
                        <asp:Button ID="btnupdate" CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Update Aircraft" />
                        <asp:Button ID="btnreset"  CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Reset"  />
                    </td>
                </tr>
            </table>
            <br />
        </div>
        <asp:GridView ID="gvdaircraft" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True">
        </asp:GridView>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>


