<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="airport.aspx.cs" Inherits="airline_management_system.airport" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title> Airport Form </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style type="text/css">
        .bg{
    background-image: linear-gradient(90deg,#12c2e9,#c471ed,#f64f59);
}
h1{
   /* text-decoration:underline 1px;*/
    padding:40px 0px 30px 0px;
}
.table-bg {
    background: rgba(255,255,255,0.31);
    box-shadow: 0 4px 30px rgba(0,0,0,0.1);
    backdrop-filter: blur(4.5px);
    -webkit-backdrop-filter: blur(4.5px);
   /* border: 1px solid rgba(255,255,255,1);*/
    text-align: center;
    border-radius: 16px;
    margin: 120px auto;
    width:800px;
}
tr{
    padding:200px;
}
    </style>
</head>
<body class="bg">
    <form id="form1" runat="server">
        <div>
            <table class="table-bg">
                <tr>
                    <td colspan="2"><h1>Airport Details</h1></td>
                </tr>
                <tr>
                    <td><h4>Airport Code :</h4></td>
                    <td>
                        <asp:TextBox ID="txtairportcode" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td><h4>Airport Name :</h4></td>
                    <td>
                        <asp:TextBox ID="txtairportname" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td><h4>City :</h4></td>
                    <td>
                        <asp:TextBox ID="txtcity" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td><h4>Country :</h4></td>
                    <td>
                        <asp:TextBox ID="txtcountry" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td><h4>Time Zone :</h4></td>
                    <td>
                        <asp:TextBox ID="txttimezone" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"  CssClass="d-flex justify-content-between">
                        <asp:Button ID="btnadd" CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Add Airport" OnClick="btnadd_Click"/>
                        <asp:Button ID="btnupdate" CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Update Airport" OnClick="btnupdate_Click" />
                        <asp:Button ID="btnreset" CssClass="btn btn-primary border mx-2 my-5" runat="server" Text="Reset" OnClick="btnreset_Click" />
                    </td>
                </tr>
            </table>
            <br />
        </div>
        <asp:GridView ID="gvdairport" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowDeleting="gvdairport_RowDeleting" OnSelectedIndexChanged="gvdairport_SelectedIndexChanged">
        </asp:GridView>
    </form>
</body>
</html>
