<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="booking.aspx.cs" Inherits="airline.adminside.booking" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Booking Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style type="text/css">
        .bg{
            background-image: linear-gradient(90deg,#12c2e9,#c471ed,#f64f59);
        }
        h1{
        /* text-decoration:underline 1px;*/
            padding:40px 0px 30px 0px;
        }
        .table-bg {
            background: rgba(255,255,255,0.31);
            box-shadow: 0 4px 30px rgba(0,0,0,0.1);
            backdrop-filter: blur(4.5px);
            -webkit-backdrop-filter: blur(4.5px);
        /* border: 1px solid rgba(255,255,255,1);*/
            text-align: center;
            border-radius: 16px;
            margin: 120px auto;
            width:800px;
        }
        tr{
            padding:200px;
        }
    </style>
</head>
<body class="bg">
    <form id="form1" runat="server">
        <table class="table-bg">
            <tr>
                <td colspan="2"><h1>Booking Details</h1></td>
            </tr>
            <tr>
                <td><h4>Passenger Name :</h4></td>
                <td>
                    <asp:DropDownList ID="ddlpassengerid" CssClass="form-control my-2 w-75" runat="server">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td><h4>Flight No :</h4></td>
                <td>
                    <asp:DropDownList ID="ddlflightno" CssClass="form-control my-2 w-75" runat="server">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td><h4>Seat No :</h4></td>
                <td>
                    <asp:TextBox ID="txtseatno" runat="server" CssClass="form-control my-2 w-75"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td><h4>Booking Status :</h4></td>
                <td>
                    <asp:RadioButtonList ID="rblbookingstatus" runat="server" CssClass="form-control my-2 w-75" RepeatDirection="Horizontal">
                        <asp:ListItem>Confirmed</asp:ListItem>
                        <asp:ListItem>Pending</asp:ListItem>
                        <asp:ListItem>Cancel</asp:ListItem>
                    </asp:RadioButtonList>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="btnupdate" runat="server" Text="Update Booking" OnClick="btnupdate_Click" CssClass="btn btn-primary border mx-2 my-5"/>
                    <asp:Button ID="btnreset" runat="server" Text="Reset" OnClick="btnreset_Click" CssClass="btn btn-primary border mx-2 my-5"/>
                </td>
            </tr>
        </table>
        <asp:GridView ID="gdvbooking" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="gdvbooking_SelectedIndexChanged">
        </asp:GridView>
    </form>
</body>
</html>
