<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="flight.aspx.cs" Inherits="airline_management_system.flight" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Flight Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style type="text/css">
.bg{
    background-image: linear-gradient(90deg,#12c2e9,#c471ed,#f64f59);
}
h1{
   /* text-decoration:underline 1px;*/
    padding:40px 0px 30px 0px;
}
.table-bg {
    background: rgba(255,255,255,0.31);
    box-shadow: 0 4px 30px rgba(0,0,0,0.1);
    backdrop-filter: blur(4.5px);
    -webkit-backdrop-filter: blur(4.5px);
   /* border: 1px solid rgba(255,255,255,1);*/
    text-align: center;
    border-radius: 16px;
    margin: 120px auto;
    width:800px;
}
tr{
    padding:200px;
}
    </style>
</head>
<body class="bg">
    <form id="form1" runat="server">
        <table class="table-bg">
            <tr>
                <td colspan="2"><h1>FLIGHT INFORMATION </h1></td>
            </tr>
            <tr>
                <td><h4>Flight No :</h4></td>
                <td>
                    <asp:TextBox ID="txtflightno" runat="server"  CssClass="form-control my-2 w-75"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td><h4>Departure Airport :</h4></td>
                <td>
                    <asp:DropDownList ID="ddldepartureairport" runat="server"  CssClass="form-control my-2 w-75">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td><h4>Departure Time :</h4></td>
                <td>
                    <asp:TextBox ID="txtdeparturetime" runat="server" TextMode="Time"  CssClass="form-control my-2 w-75"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td><h4>Arrival Airport :</h4></td>
                <td>
                    <asp:DropDownList ID="ddlarrivalairport" runat="server"  CssClass="form-control my-2 w-75">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td><h4>Arrival Time :</h4></td>
                <td>
                    <asp:TextBox ID="txtarrivaltime" runat="server" TextMode="Time"  CssClass="form-control my-2 w-75"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td><h4>Aircraft :</h4></td>
                <td>
                    <asp:DropDownList ID="ddlaircraftid" runat="server"  CssClass="form-control my-2 w-75">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="btnadd" runat="server" Text="Add Flight"  CssClass="btn btn-primary border mx-2 my-5" OnClick="btnadd_Click" />
                    <asp:Button ID="btnupdate" runat="server" Text="Update Flight"  CssClass="btn btn-primary border mx-2 my-5" OnClick="btnupdate_Click"/>
                    <asp:Button ID="btnreset" runat="server" Text="Reset"  CssClass="btn btn-primary border mx-2 my-5" OnClick="btnreset_Click" />
                </td>
            </tr>
        </table>
        <asp:GridView ID="gdvflight" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="gdvflight_SelectedIndexChanged">
        </asp:GridView>
    </form>
</body> 
</html>

